/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.xk8s.csi.secretsstore.secretproviderclasses.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SecretProviderClassStatus defines the observed state of SecretProviderClass
 */
@ApiModel(description = "SecretProviderClassStatus defines the observed state of SecretProviderClass")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-24T00:06:50.126Z[Etc/UTC]")
public class V1alpha1SecretProviderClassStatus {
  public static final String SERIALIZED_NAME_BY_POD = "byPod";
  @SerializedName(SERIALIZED_NAME_BY_POD)
  private List<V1alpha1SecretProviderClassStatusByPod> byPod = null;


  public V1alpha1SecretProviderClassStatus byPod(List<V1alpha1SecretProviderClassStatusByPod> byPod) {
    
    this.byPod = byPod;
    return this;
  }

  public V1alpha1SecretProviderClassStatus addByPodItem(V1alpha1SecretProviderClassStatusByPod byPodItem) {
    if (this.byPod == null) {
      this.byPod = new ArrayList<>();
    }
    this.byPod.add(byPodItem);
    return this;
  }

   /**
   * Get byPod
   * @return byPod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1SecretProviderClassStatusByPod> getByPod() {
    return byPod;
  }


  public void setByPod(List<V1alpha1SecretProviderClassStatusByPod> byPod) {
    this.byPod = byPod;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1SecretProviderClassStatus v1alpha1SecretProviderClassStatus = (V1alpha1SecretProviderClassStatus) o;
    return Objects.equals(this.byPod, v1alpha1SecretProviderClassStatus.byPod);
  }

  @Override
  public int hashCode() {
    return Objects.hash(byPod);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1SecretProviderClassStatus {\n");
    sb.append("    byPod: ").append(toIndentedString(byPod)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

