/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.xk8s.csi.secretsstore.secretproviderclasses.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.*;

/**
 * SecretObject defines the desired state of synced K8s secret objects
 */
@ApiModel(description = "SecretObject defines the desired state of synced K8s secret objects")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-24T00:06:50.126Z[Etc/UTC]")
public class V1alpha1SecretProviderClassSpecSecretObjects {
  public static final String SERIALIZED_NAME_ANNOTATIONS = "annotations";
  @SerializedName(SERIALIZED_NAME_ANNOTATIONS)
  private Map<String, String> annotations = null;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  private List<V1alpha1SecretProviderClassSpecData> data = null;

  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  private Map<String, String> labels = null;

  public static final String SERIALIZED_NAME_SECRET_NAME = "secretName";
  @SerializedName(SERIALIZED_NAME_SECRET_NAME)
  private String secretName;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;


  public V1alpha1SecretProviderClassSpecSecretObjects annotations(Map<String, String> annotations) {
    
    this.annotations = annotations;
    return this;
  }

  public V1alpha1SecretProviderClassSpecSecretObjects putAnnotationsItem(String key, String annotationsItem) {
    if (this.annotations == null) {
      this.annotations = new HashMap<>();
    }
    this.annotations.put(key, annotationsItem);
    return this;
  }

   /**
   * annotations of k8s secret object
   * @return annotations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "annotations of k8s secret object")

  public Map<String, String> getAnnotations() {
    return annotations;
  }


  public void setAnnotations(Map<String, String> annotations) {
    this.annotations = annotations;
  }


  public V1alpha1SecretProviderClassSpecSecretObjects data(List<V1alpha1SecretProviderClassSpecData> data) {
    
    this.data = data;
    return this;
  }

  public V1alpha1SecretProviderClassSpecSecretObjects addDataItem(V1alpha1SecretProviderClassSpecData dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1SecretProviderClassSpecData> getData() {
    return data;
  }


  public void setData(List<V1alpha1SecretProviderClassSpecData> data) {
    this.data = data;
  }


  public V1alpha1SecretProviderClassSpecSecretObjects labels(Map<String, String> labels) {
    
    this.labels = labels;
    return this;
  }

  public V1alpha1SecretProviderClassSpecSecretObjects putLabelsItem(String key, String labelsItem) {
    if (this.labels == null) {
      this.labels = new HashMap<>();
    }
    this.labels.put(key, labelsItem);
    return this;
  }

   /**
   * labels of K8s secret object
   * @return labels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "labels of K8s secret object")

  public Map<String, String> getLabels() {
    return labels;
  }


  public void setLabels(Map<String, String> labels) {
    this.labels = labels;
  }


  public V1alpha1SecretProviderClassSpecSecretObjects secretName(String secretName) {
    
    this.secretName = secretName;
    return this;
  }

   /**
   * name of the K8s secret object
   * @return secretName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "name of the K8s secret object")

  public String getSecretName() {
    return secretName;
  }


  public void setSecretName(String secretName) {
    this.secretName = secretName;
  }


  public V1alpha1SecretProviderClassSpecSecretObjects type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * type of K8s secret object
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "type of K8s secret object")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1SecretProviderClassSpecSecretObjects v1alpha1SecretProviderClassSpecSecretObjects = (V1alpha1SecretProviderClassSpecSecretObjects) o;
    return Objects.equals(this.annotations, v1alpha1SecretProviderClassSpecSecretObjects.annotations) &&
        Objects.equals(this.data, v1alpha1SecretProviderClassSpecSecretObjects.data) &&
        Objects.equals(this.labels, v1alpha1SecretProviderClassSpecSecretObjects.labels) &&
        Objects.equals(this.secretName, v1alpha1SecretProviderClassSpecSecretObjects.secretName) &&
        Objects.equals(this.type, v1alpha1SecretProviderClassSpecSecretObjects.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(annotations, data, labels, secretName, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1SecretProviderClassSpecSecretObjects {\n");
    sb.append("    annotations: ").append(toIndentedString(annotations)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    secretName: ").append(toIndentedString(secretName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

