/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.xk8s.csi.secretsstore.secretproviderclasses.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ByPodStatus defines the state of SecretProviderClass as seen by an individual controller
 */
@ApiModel(description = "ByPodStatus defines the state of SecretProviderClass as seen by an individual controller")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-24T00:06:50.126Z[Etc/UTC]")
public class V1alpha1SecretProviderClassStatusByPod {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAMESPACE = "namespace";
  @SerializedName(SERIALIZED_NAME_NAMESPACE)
  private String namespace;


  public V1alpha1SecretProviderClassStatusByPod id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * id of the pod that wrote the status
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "id of the pod that wrote the status")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public V1alpha1SecretProviderClassStatusByPod namespace(String namespace) {
    
    this.namespace = namespace;
    return this;
  }

   /**
   * namespace of the pod that wrote the status
   * @return namespace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "namespace of the pod that wrote the status")

  public String getNamespace() {
    return namespace;
  }


  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1SecretProviderClassStatusByPod v1alpha1SecretProviderClassStatusByPod = (V1alpha1SecretProviderClassStatusByPod) o;
    return Objects.equals(this.id, v1alpha1SecretProviderClassStatusByPod.id) &&
        Objects.equals(this.namespace, v1alpha1SecretProviderClassStatusByPod.namespace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, namespace);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1SecretProviderClassStatusByPod {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

