/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.xk8s.csi.secretsstore.secretproviderclasses.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.*;

/**
 * SecretProviderClassSpec defines the desired state of SecretProviderClass
 */
@ApiModel(description = "SecretProviderClassSpec defines the desired state of SecretProviderClass")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-24T00:06:50.126Z[Etc/UTC]")
public class V1alpha1SecretProviderClassSpec {
  public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
  @SerializedName(SERIALIZED_NAME_PARAMETERS)
  private Map<String, String> parameters = null;

  public static final String SERIALIZED_NAME_PROVIDER = "provider";
  @SerializedName(SERIALIZED_NAME_PROVIDER)
  private String provider;

  public static final String SERIALIZED_NAME_SECRET_OBJECTS = "secretObjects";
  @SerializedName(SERIALIZED_NAME_SECRET_OBJECTS)
  private List<V1alpha1SecretProviderClassSpecSecretObjects> secretObjects = null;


  public V1alpha1SecretProviderClassSpec parameters(Map<String, String> parameters) {
    
    this.parameters = parameters;
    return this;
  }

  public V1alpha1SecretProviderClassSpec putParametersItem(String key, String parametersItem) {
    if (this.parameters == null) {
      this.parameters = new HashMap<>();
    }
    this.parameters.put(key, parametersItem);
    return this;
  }

   /**
   * Configuration for specific provider
   * @return parameters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Configuration for specific provider")

  public Map<String, String> getParameters() {
    return parameters;
  }


  public void setParameters(Map<String, String> parameters) {
    this.parameters = parameters;
  }


  public V1alpha1SecretProviderClassSpec provider(String provider) {
    
    this.provider = provider;
    return this;
  }

   /**
   * Configuration for provider name
   * @return provider
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Configuration for provider name")

  public String getProvider() {
    return provider;
  }


  public void setProvider(String provider) {
    this.provider = provider;
  }


  public V1alpha1SecretProviderClassSpec secretObjects(List<V1alpha1SecretProviderClassSpecSecretObjects> secretObjects) {
    
    this.secretObjects = secretObjects;
    return this;
  }

  public V1alpha1SecretProviderClassSpec addSecretObjectsItem(V1alpha1SecretProviderClassSpecSecretObjects secretObjectsItem) {
    if (this.secretObjects == null) {
      this.secretObjects = new ArrayList<>();
    }
    this.secretObjects.add(secretObjectsItem);
    return this;
  }

   /**
   * Get secretObjects
   * @return secretObjects
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1alpha1SecretProviderClassSpecSecretObjects> getSecretObjects() {
    return secretObjects;
  }


  public void setSecretObjects(List<V1alpha1SecretProviderClassSpecSecretObjects> secretObjects) {
    this.secretObjects = secretObjects;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1SecretProviderClassSpec v1alpha1SecretProviderClassSpec = (V1alpha1SecretProviderClassSpec) o;
    return Objects.equals(this.parameters, v1alpha1SecretProviderClassSpec.parameters) &&
        Objects.equals(this.provider, v1alpha1SecretProviderClassSpec.provider) &&
        Objects.equals(this.secretObjects, v1alpha1SecretProviderClassSpec.secretObjects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parameters, provider, secretObjects);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1SecretProviderClassSpec {\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    secretObjects: ").append(toIndentedString(secretObjects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

