/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.xk8s.csi.secretsstore.secretproviderclasses.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * SecretObjectData defines the desired state of synced K8s secret object data
 */
@ApiModel(description = "SecretObjectData defines the desired state of synced K8s secret object data")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-24T00:06:50.126Z[Etc/UTC]")
public class V1alpha1SecretProviderClassSpecData {
  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_OBJECT_NAME = "objectName";
  @SerializedName(SERIALIZED_NAME_OBJECT_NAME)
  private String objectName;


  public V1alpha1SecretProviderClassSpecData key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * data field to populate
   * @return key
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "data field to populate")

  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public V1alpha1SecretProviderClassSpecData objectName(String objectName) {
    
    this.objectName = objectName;
    return this;
  }

   /**
   * name of the object to sync
   * @return objectName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "name of the object to sync")

  public String getObjectName() {
    return objectName;
  }


  public void setObjectName(String objectName) {
    this.objectName = objectName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1SecretProviderClassSpecData v1alpha1SecretProviderClassSpecData = (V1alpha1SecretProviderClassSpecData) o;
    return Objects.equals(this.key, v1alpha1SecretProviderClassSpecData.key) &&
        Objects.equals(this.objectName, v1alpha1SecretProviderClassSpecData.objectName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, objectName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1SecretProviderClassSpecData {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    objectName: ").append(toIndentedString(objectName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

